events {}

http {
    upstream education_backend {
        server education-service:8081;
    }

    upstream squad_backend {
        server squad-service:8082;
    }

    server {
        listen 80;

        location /api/v1/squads/ {
            proxy_pass http://squad_backend/api/v1/squads/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/regions/ {
            proxy_pass http://squad_backend/api/v1/regions/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/roles/ {
            proxy_pass http://squad_backend/api/v1/roles/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/positions/ {
            proxy_pass http://squad_backend/api/v1/positions/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/users/ {
            proxy_pass http://squad_backend/api/v1/users/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/education/ {
            proxy_pass http://education_backend/api/v1/education/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://squad_backend/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}