events {}

http {
    # Группа серверов для Education Service
    upstream education_backend {
        server education-service:8081;  # имя контейнера из docker-compose
    }

    server {
        listen 80;

        # Проксирование API-запросов
        location /api/v1/education/ {
            proxy_pass http://education_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Отдача статики Angular (фронтенд)
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;  # для SPA-routing
        }
    }
}